baseURL = "http://cdevenish.github.io/r_stuff/"
publishDir = "docs"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Miscellaneous R stuff"
theme = "hugo-theme-techdoc"

hasCJKLanguage = true
metaDataFormat = "yaml"

pygmentsUseClasses = true
pygmentsCodefences = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Params]

    # Souce Code repository section
    # description = "Examples of R packages and some of my functions"
    github_repository = "https://github.com/Cdevenish/r_stuff"
    # version = "0.2.1"

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    # github_doc_repository = "https://github.com/thingsym/hugo-theme-techdoc"

    # Analytic section
    google_analytics_id = "" # Your Google Analytics tracking id
    tag_manager_container_id = "" # Your Google Tag Manager container id
    google_site_verification = "" # Your Google Site Verification

    # Theme settings section
    dateformat = "" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    menu_exclusion = ["archives", "blog", "entry", "post", "posts"]


# Global menu section
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

#[[menu.main]]
#    name = "Github"
#    url = "https://twitter.com/thingsym"
#    weight = 2

# Can put menu items here - eg web links, or can have them from .rmd pages in the main content folder